import { config as c, priceLabel } from '../lib/config.mjs';
import { icon, escape, operator, faq } from './shared.mjs';
const date = () => new Date(c.effectiveDate+'T12:00:00Z').toLocaleDateString('en-CA',{year:'numeric',month:'long',day:'numeric'});
const contact = (privacy=false) => (privacy?c.privacyEmail:c.supportEmail) ? `<a href="mailto:${escape(privacy?c.privacyEmail:c.supportEmail)}">${escape(privacy?c.privacyEmail:c.supportEmail)}</a>` : `<a href="support.html#contact">${privacy?'Contact our privacy team':'Contact FirstLane support'}</a>`;
const days = (n,unit='days') => Number.isInteger(n) ? `${n} ${unit}` : null;
const table = (headers, rows) => `<table class="data-table"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<${i===0?'th scope="row"':'td'}>${v}</${i===0?'th':'td'}>`).join('')}</tr>`).join('')}</tbody></table>`;
function heading(eyebrow,title,description,meta=false){return `<div class="wrap page-heading"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p>${meta?`<div class="page-meta">Last updated ${date()} <span>·</span> FirstLane app &amp; website</div>`:''}</div>`;}
function policy(title,description,intro,sections){ return heading('YOUR PEACE OF MIND',title,description,true)+`<div class="wrap legal-layout"><nav class="legal-nav" aria-label="On this page"><strong>ON THIS PAGE</strong>${sections.map(([id,h])=>`<a href="#${id}">${h}</a>`).join('')}</nav><article class="legal-content"><div class="policy-intro">${intro}</div>${sections.map(([id,h,body])=>`<section class="policy-section" id="${id}"><h2>${h}</h2>${body}</section>`).join('')}<div class="policy-footer">Questions about this page? ${contact(title==='Privacy policy')}</div></article></div>`; }
export function privacy(){return policy('Privacy policy','A clear view of the information FirstLane uses, why it is needed, and the choices you have.',`<strong>Your practice is personal.</strong><p>This website does not run advertising pixels or analytics trackers. We use information to provide FirstLane, protect accounts, recognise purchases and respond when you ask for help. Account deletion is available <a href="delete-account.html">here</a>.</p>`,[
 ['who','1. Who is responsible',`<p>FirstLane is a product of ${operator()} (“FirstLane”, “we”, “us”). This policy covers the FirstLane mobile app and this website.</p>${c.businessAddress?`<p>Business contact address: ${escape(c.businessAddress)}.</p>`:''}<p>${c.publisherDisclosure?escape(c.publisherDisclosure):'The seller shown on your App Store or Google Play listing may be a separate authorised publisher. The store listing and your receipt identify the seller responsible for that store transaction. Our role is to develop and operate FirstLane and support your use of the product.'}</p><p>Privacy questions and requests: ${contact(true)}.</p>`],
 ['information','2. Information FirstLane uses',table(['Information','Purpose'],[
  ['Account and identity','Your email address, account ID, optional display name, preferences and authentication records are used to create, secure and maintain your account. Supabase handles authentication.'],
  ['Study activity','Practice answers, session history, bookmarks, review lists and selected topics are used to provide study features. Some study data stays on your device; synced progress is stored against your account when you use the sync feature.'],
  ['Purchases and access','Store transaction identifiers, product and entitlement identifiers, purchase or refund status and related account references are used to recognise and restore valid purchases. Apple or Google processes payment; FirstLane does not receive your full payment-card details.'],
  ['Support and content reports','Your contact email, the information in your message, question references and relevant troubleshooting details allow us to respond and investigate. Please do not send passwords, card numbers or verification codes in support messages.'],
  ['Security and delivery','Web servers and service providers process technical information such as IP address, request time and browser/device information to deliver the service, limit abuse and investigate failures.'],
  ['Website preferences','A local preference records whether you have paused website animations. This is not an advertising identifier. Account-deletion verification codes and access tokens are held only temporarily during the web flow, not stored in browser local storage.']
 ])],
 ['purposes','3. How and why we use it',`<p>We use the information described above to provide the account and learning features you request, send account verification or recovery messages, deliver content you have purchased, maintain progress, provide support and protect FirstLane against misuse. We also use limited records when necessary to handle disputes or comply with applicable obligations.</p><p>We do not use your study answers to make credit, employment or insurance decisions. We do not sell your personal information. This website does not run behavioural advertising or cross-site tracking.</p><p>Where your consent is required for a particular activity, we request it separately. Sending a support or deletion request does not sign you up for marketing. Withdrawing optional consent does not affect processing already carried out lawfully or processing needed to fulfil your request.</p>`],
 ['providers','4. Service providers and sharing',table(['Provider or recipient','Role'],[
 ['Supabase','Account authentication, database, server functions and content storage. It processes account details and related application records needed to provide these services.'],
 ['RevenueCat','Purchase and entitlement management. It processes app-user and store-purchase references used to check paid access.'],
 ['Apple / Google','App distribution, store checkout, transaction handling and refunds under their own terms and privacy policies.'],
 [escape(c.providers.websiteHost||'Website hosting provider'),'Delivers website files and server functions and processes technical request information.'],
 [escape(c.providers.authenticationEmail||'Authentication email provider'),'Delivers verification and account-recovery messages.'],
 ['Resend','Delivers messages from the website contact form to our support mailbox. The email address and message you submit are included.'],
 ['Cloudflare Turnstile','Provides abuse prevention on the support and account-deletion forms. It processes technical signals to help distinguish legitimate requests from automated abuse.']
 ])+`<p>We may share limited information with an authorised app publisher for purchase support, with professional advisers where necessary, or when disclosure is required by law. A business transfer involving FirstLane may require transfer of relevant records with appropriate protections and notice where required.</p>`],
 ['retention','5. How long information is kept',table(['Record','Retention and deletion'],[
 ['Account and synced study records',`Retained while your account is active. Following a verified deletion, active account and associated profile, synced practice and account-linked report records are removed${days(c.retention.deletionDays)?' within '+days(c.retention.deletionDays):' as the deletion is processed'}.`],
 ['Backups',days(c.retention.backupDays)?`Restricted backup copies age out within ${days(c.retention.backupDays)}. They are not used to restore your active account after a deletion request. If a backup is restored for disaster recovery, deletion records must be reapplied.`:'Restricted backups follow a limited rotation period. Deleted account information is not used to reactivate your account. Contact the privacy team for information about a backup affecting your request.'],
 ['Security logs',days(c.retention.securityLogDays)?`Routine security logs are retained for up to ${days(c.retention.securityLogDays)}, unless an identified incident or legal obligation requires a limited extension.`:'Technical logs are retained only as needed to protect the service, investigate identified incidents or meet applicable obligations.'],
 ['Support correspondence',days(c.retention.supportMonths,'months')?`Support correspondence is retained for up to ${days(c.retention.supportMonths,'months')} after the matter is closed, unless a dispute or legal obligation requires longer retention.`:'Support correspondence is kept for the time needed to resolve your request and handle related follow-up or disputes.'],
 ['Transaction and audit records',days(c.retention.transactionYears,'years')?`Limited transaction, refund and audit information may be retained for up to ${days(c.retention.transactionYears,'years')} for ${escape(c.retention.transactionPurpose)}. Access is restricted and it is not used to restore deleted study history.`:'Limited transaction-event, refund and audit information may need to be retained for accounting, fraud prevention, dispute handling or legal obligations. We explain any relevant exception when responding to your request.'],
 ['Records held by processors',days(c.retention.processorDeletionDays)?`Where a processor acts on our behalf, account-data removal requests are completed within ${days(c.retention.processorDeletionDays)}, subject to specific retention obligations. Apple and Google retain their own purchase records under their policies.`:'We coordinate account-data removal with processors acting on our behalf, subject to applicable retention obligations. Apple and Google retain their own store and purchase records under their policies.']
 ])+`<p>We limit retained information to what is necessary for the stated purpose. Records no longer needed are deleted or appropriately anonymised. A legal hold can require an otherwise scheduled deletion to be deferred; we explain this where legally permitted.</p>`],
 ['choices','6. Your choices and requests',`<p>You can update available account details and preferences in the app. You can ask us about access to your information, correction, deletion, a copy of your data, or objections to processing where applicable. We may need to verify that the account belongs to you before disclosing or changing personal information.</p><p>Use ${contact(true)} for a privacy request. We respond within the period applicable to your request and location and explain any lawful refusal or extension. You can raise an unresolved privacy concern with the relevant privacy regulator, including the Office of the Privacy Commissioner of Canada where applicable.</p><p>To remove an account, use <strong>Profile → Your account → Delete account</strong> in FirstLane, or use the <a href="delete-account.html">web account-deletion flow</a>. You do not need to reinstall the app to start from the website.</p><p>Deleting the account removes access to that account and its synced study history. It does not request an Apple or Google refund, and may prevent purchase restoration to that deleted FirstLane account. Local copies on an offline device are not remotely erased by this website; remove the app’s local data on devices you control.</p>`],
 ['international','7. International processing',`<p>FirstLane and its service providers may process information outside your province or country. ${c.providers.processingCountries?'The configured processing locations include '+escape(c.providers.processingCountries)+'.':'The location depends on the hosting and service-provider systems involved.'} Information may be subject to laws and lawful access requests in those locations.</p><p>We remain responsible for selecting and overseeing providers that process information on our behalf and use contractual and operational safeguards appropriate to the information. Contact us for details relevant to your information or request.</p>`],
 ['security','8. Keeping information secure',`<p>We use encrypted transport, authenticated account actions and access controls intended to protect information. The website does not contain privileged database credentials. Deletion requires verification and an explicit confirmation. No service can guarantee perfect security.</p><p>Keep your email account and device secure. Enter a verification code only into a FirstLane sign-in or deletion screen you opened yourself. Our support team will not ask you to send them a password or code.</p>`],
 ['younger-users','9. Younger learners',`<p>FirstLane is intended for learners aged ${c.minimumAge} or older. Where you are below the age at which you can independently accept the applicable terms, a parent or guardian should review the service with you. We do not intend to collect account information from children below our stated minimum age. Contact us if you believe such information was provided so we can review and remove it as appropriate.</p>`],
 ['changes','10. Changes and contact',`<p>We update this policy when the service or its data practices change. The date at the top identifies the current version. Where a change requires additional notice or consent, we provide it before applying the relevant change.</p><p>Privacy contact: ${contact(true)}.<br>Product operator: ${operator()}${c.businessAddress?'<br>'+escape(c.businessAddress):''}.</p>`]
]);}
export function terms(){return policy('Terms of service','The important details about using FirstLane and buying Ontario G1 Complete.',`<strong>${priceLabel}. Once. Not a subscription.</strong><p>Ontario G1 Complete is a one-time purchase through the app. No automatic renewal and no scheduled expiry on the Ontario pack. It is an independent learning tool—not a promise that you will pass.</p>`,[
 ['about','1. About these terms',`<p>These terms apply to your use of the FirstLane app and website, provided by ${operator()}. By using FirstLane, you agree to these terms. Please read the <a href="privacy.html">Privacy policy</a> for information about data handling. Mandatory rights under applicable consumer law are not limited by these terms.</p><p>${c.publisherDisclosure?escape(c.publisherDisclosure):'The app-store listing identifies the authorised publisher or seller for a store transaction. That publisher may be a separate company from the product operator.'} Apple’s and Google’s applicable store terms also apply to downloads and purchases made through their services.</p>`],
 ['independent','2. Independent preparation',`<p>FirstLane provides Ontario G1 practice and study material. It is not a government agency, the official Ontario G1 test, a licence provider or a driving school. FirstLane is not affiliated with or endorsed by Ontario’s Ministry of Transportation or DriveTest.</p><p>Questions, explanations, mock sessions and progress indicators are learning aids. They are not official exam questions, official test results or a guarantee of passing. Consult current official guidance for licensing requirements and road rules. Do not use the app while driving.</p>`],
 ['accounts','3. Eligibility and accounts',`<p>FirstLane is intended for learners aged ${c.minimumAge} or older. When your age or local law requires it, obtain a parent’s or guardian’s involvement before accepting these terms or making a purchase.</p><p>Provide accurate account information and keep your sign-in details secure. You are responsible for activity you authorise on your account. Contact support when you suspect unauthorised use. Some features are available as a guest; others require an account, an internet connection or a valid purchase.</p>`],
 ['free','4. Free access',`<p>You can try 10 guest questions. A free account includes a fixed set of 40 Ontario practice questions, explanations and saved free progress. The free set is not a rotating daily allowance and is not a time-limited subscription trial. You do not need to enter payment-card details to use free access.</p>`],
 ['complete','5. Ontario G1 Complete',`<p>Ontario G1 Complete has a Canadian reference price of <strong>${priceLabel}</strong> and is a one-time, non-consumable in-app purchase. It unlocks the Ontario pack and associated paid study features, including topic practice, mock sessions, mistake review, bookmarks and downloaded offline study.</p><p>It is not an automatically renewing subscription. There is no scheduled expiry on valid Ontario access. Access remains subject to a valid, non-refunded purchase, applicable store rules, account security and service availability. “No scheduled expiry” does not promise that every device or online service will be supported forever.</p><p>New jurisdictions are separate packs and are not included unless expressly stated. No recurring charge is created by buying Ontario G1 Complete.</p>`],
 ['payments','6. Payments, refunds and restoration',`<p>Purchases take place inside the app through Apple or Google, not through this website. The store shows the final price in the applicable currency and any taxes before you confirm. The amount shown in the store checkout controls that transaction.</p><p>Use the relevant store’s refund process. Eligibility is determined under its policies and applicable consumer law; a refund is not automatically granted. Refunded, reversed or invalid transactions may lose the related paid access.</p><p>To restore a valid purchase, sign in to the original FirstLane account, use the relevant store account and follow <a href="support.html#purchases">the restoration instructions</a>. Cross-platform transfer is not promised. Do not buy again simply because access has not yet refreshed; contact support first.</p><p>Deleting a FirstLane account does not initiate a refund. It removes account-linked access records and may prevent restoring a purchase to that deleted FirstLane account. Your store retains its own transaction history.</p>`],
 ['offline','7. Content, updates and availability',`<p>Downloaded material can be used offline, but a connection is needed for account actions, purchases, initial downloads, updates, progress sync and periodic access verification. Offline access is not a promise of indefinite use without reconnecting.</p><p>We may correct content and make changes for safety, quality, security or compatibility. We aim to preserve the essential value of purchased access. Where a material change or discontinuation affects that value, we provide appropriate notice and any remedy required by applicable law.</p><p>Practice content may contain errors or become outdated. Report a question through the app or <a href="support.html#content">Support</a>. Technical problems or maintenance may temporarily interrupt service.</p>`],
 ['use','8. Acceptable use and ownership',`<p>We grant you a personal, limited, non-exclusive right to use FirstLane and legitimately unlocked content for your own study. FirstLane software, branding, original text and artwork belong to their respective rights holders. Government and third-party material retains its applicable rights and terms.</p><p>Do not bypass access controls, redistribute or sell paid material, scrape the service in bulk, interfere with infrastructure, attempt unauthorised account access, or use the service unlawfully. These restrictions do not override rights that the law expressly gives you.</p>`],
 ['ending','9. Ending access and deleting an account',`<p>You can stop using FirstLane at any time and request account deletion <a href="delete-account.html">on this website</a> or in the app. Removing the app from a device is not the same as deleting your server account.</p><p>We may restrict access when reasonably necessary to address a serious breach, abuse, security risk or legal obligation. Where appropriate and lawful, we explain the reason and provide a route to resolve the issue. We do not turn a one-time purchase into a recurring subscription.</p>`],
 ['rights','10. Responsibility and consumer rights',`<p>FirstLane is a study aid, and you remain responsible for safe driving and meeting official licensing requirements. We do not guarantee an exam result, uninterrupted availability, or compatibility with every device.</p><p>Nothing in these terms excludes a warranty, remedy or liability that cannot lawfully be excluded, including mandatory rights relating to digital content, consumer protection, privacy, fraud or personal injury. Any exclusion or limitation applies only to the extent permitted by applicable law.</p><p>Contact us about an issue so we can investigate and seek a reasonable resolution. These terms do not require you to waive access to courts, mandatory complaint routes, or any other non-waivable consumer rights.</p>`],
 ['law','11. Law and changes',`<p>${c.governingLaw?escape(c.governingLaw):'Applicable law and mandatory consumer protections determine your rights. Nothing here prevents you from bringing a claim in a jurisdiction or forum to which you are legally entitled.'}</p><p>We may update these terms as FirstLane changes. Material changes will be communicated where required and will not retrospectively remove mandatory rights. The date above identifies this version.</p>`],
 ['contact','12. Contact',`<p>${operator()}${c.businessAddress?'<br>'+escape(c.businessAddress):''}<br>${contact()}</p>`]
]);}
const contactForm = `<div class="form-card" id="contact"><div class="eyebrow">A HUMAN ON THE OTHER END</div><h2>Let’s get it sorted.</h2><p>Tell us what happened. Include useful details, but never your password, verification code or full card information.</p><form id="support-form" novalidate><div class="field"><label for="support-email">Your email address</label><input id="support-email" name="email" type="email" autocomplete="email" maxlength="254" required placeholder="The address we can reply to"></div><div class="field"><label for="support-topic">What do you need help with?</label><select id="support-topic" name="topic" required><option value="account">My account</option><option value="purchase">Purchase or restore</option><option value="content">Report a question</option><option value="privacy">Privacy or data request</option><option value="deletion">Help with account deletion</option><option value="other">Something else</option></select></div><div class="field"><label for="support-message">Your message</label><textarea id="support-message" name="message" minlength="10" maxlength="4000" required placeholder="A little context helps us help you."></textarea><small>For a question report, include its question ID when available. Up to 4,000 characters.</small></div><div class="honeypot" aria-hidden="true"><label for="support-company">Leave this empty</label><input id="support-company" name="company" type="text" tabindex="-1" autocomplete="off"></div><p class="form-privacy">We use your email and message to respond to this request, as explained in our <a href="privacy.html">Privacy policy</a>. This does not subscribe you to marketing.</p><div class="captcha-container" data-captcha="support"></div><button type="submit" class="button dark" id="support-submit">Send message ${icon('arrow')}</button><div class="form-status" id="support-status" role="status" aria-live="polite"></div><noscript><p class="service-unavailable">JavaScript is needed for this secure form. Use the contact details on this page for another way to reach us.</p></noscript></form></div>`;
export function support(){return heading('FIRSTLANE SUPPORT','A little help.<br><em>A clearer way forward.</em>','Account questions, purchase hiccups or a practice question that needs another look. Start here.')+`<div class="wrap support-layout"><div><div class="support-cards"><a class="support-card" href="#purchases">${icon('refresh')}<strong>Purchase &amp; restore</strong><p>Paid, but still locked? Let’s check.</p></a><a class="support-card" href="delete-account.html">${icon('trash')}<strong>Delete an account</strong><p>Your account, on your terms.</p></a><a class="support-card" href="#content">${icon('book')}<strong>Report a question</strong><p>Help us get the details right.</p></a><a class="support-card" href="privacy.html">${icon('shield')}<strong>Privacy &amp; your data</strong><p>Clear information and control.</p></a></div>
 <section id="purchases" class="help-list"><h2>Paid, but Complete is locked?</h2><ol><li>Sign in to the FirstLane account you used for the purchase.</li><li>Check that your device uses the App Store or Google Play account that made the purchase.</li><li>Connect to the internet. Open <strong>Your account → Plan &amp; billing</strong> and use the restore or refresh-access action.</li><li>Still locked? Send us the platform, approximate purchase date and store order reference. Do not send a full receipt containing unrelated personal or financial details.</li></ol><p>Please contact us before buying again. Purchase access may need to refresh, and paying twice is not the solution.</p></section>
 <div class="help-list">${faq([
 ['How do I ask for a refund?', '<p>Start with the store that processed the purchase: <a href="https://support.apple.com/118223" target="_blank" rel="noopener noreferrer">Apple refund help</a> or <a href="https://support.google.com/googleplay/answer/2479637" target="_blank" rel="noopener noreferrer">Google Play refund help</a>. The store and applicable law determine eligibility. Account deletion does not automatically request a refund.</p>'],
 ['My verification email hasn’t arrived.', '<p>Check spam or junk, make sure the address is correct, and wait for the resend timer. Request a new code if needed. Use only the most recent code. Never send verification codes to support.</p>'],
 ['Can I move between iPhone and Android?', '<p>Use the same FirstLane account to access available synced history. Purchase recognition also depends on the original store identity and supported entitlement behaviour. Cross-platform purchase transfer is not promised; contact support before buying again.</p>'],
 ['I no longer have the app installed.', '<p>You can use the <a href="delete-account.html">account-deletion page</a> without reinstalling FirstLane. Other account or privacy questions can be sent using the contact form.</p>']
 ])}</div><section id="content" class="help-list"><h2>Something in a question looks wrong?</h2><p>Send the question ID, topic, wording that concerns you, and any relevant official source. The in-app report action is also available. We review reports before making content changes.</p></section>${c.supportEmail?`<div class="help-list"><h2>Prefer email?</h2><p>${contact()}</p></div>`:''}</div>${contactForm}</div>`;}
export function deletion(){return heading('YOUR ACCOUNT. YOUR CHOICE.','Delete your<br><em>FirstLane account.</em>','You don’t need the app installed to do this. Verify your email address, review what deletion means, and confirm your choice.')+`<div class="wrap deletion-layout"><div class="deletion-copy"><h2>What gets deleted?</h2><p>Deleting your account removes your sign-in account and account-linked profile, synced practice history, preferences and reports from FirstLane’s active application database.</p><ul><li>Your FirstLane account can no longer be used to sign in.</li><li>Synced practice history and account-linked reports are removed.</li><li>Account-linked purchase-access records are removed; restoration to that deleted FirstLane account may no longer be possible.</li></ul><div class="deletion-warning"><strong>This is permanent. It is not a refund request.</strong><p>We cannot recover deleted study history for you. Apple or Google keeps its own purchase records. Use the store’s process for a refund; deleting FirstLane does not create one.</p></div><h2>What may remain?</h2><p>Limited transaction-event, refund, security and legal records may be retained for specific obligations or dispute handling. Restricted backups expire under the retention schedule, and processor-held records follow the relevant removal process. See <a href="privacy.html#retention">retention and deletion details</a>.</p><p>Deleting from this website cannot remotely erase study data on an offline device. Remove local FirstLane data or uninstall the app on devices you control.</p><h2>How long does it take?</h2><p>${days(c.retention.deletionDays)?'Active account deletion is completed within '+days(c.retention.deletionDays)+' of a verified request.':'After confirmation, FirstLane attempts to remove your active account immediately. The website only confirms deletion after the account service confirms it.'} Other eligible records and backups follow the <a href="privacy.html#retention">retention schedule</a>.</p><h2>Prefer to do it in the app?</h2><p>Open <strong>Profile → Your account → Delete account</strong> and follow the confirmation steps.</p><h2>Lost access to your email?</h2><p>Use <a href="support.html#contact">Support</a> for help verifying account ownership another way. Do not send us a password or verification code.</p></div>
 <div class="form-card deletion-form"><div class="eyebrow">SECURE ACCOUNT DELETION</div><div class="delete-steps" aria-label="Deletion steps"><span class="current" data-step="1"><i>1</i> Your email</span><span data-step="2"><i>2</i> Verify</span><span data-step="3"><i>3</i> Confirm</span></div>
 <section id="delete-email-panel"><h2>First, let’s verify it’s you.</h2><p class="form-privacy">Use the email address linked to your FirstLane account. Enter the code only on this page—not in a support message.</p><form id="delete-email-form" novalidate><div class="field"><label for="delete-email">FirstLane account email</label><input type="email" name="email" id="delete-email" autocomplete="email" maxlength="254" required placeholder="Your FirstLane email address"></div><div class="honeypot" aria-hidden="true"><label for="delete-company">Leave this empty</label><input name="company" id="delete-company" tabindex="-1" autocomplete="off"></div><div class="captcha-container" data-captcha="deletion"></div><button class="button dark" type="submit">Send verification code ${icon('arrow')}</button></form></section>
 <section id="delete-code-panel" hidden><h2>Check your inbox.</h2><p class="form-privacy">If this address is linked to a FirstLane account, a code has been sent. Use the most recent code and keep this page open.</p><form id="delete-code-form" novalidate><div class="field"><label for="delete-code">Email verification code</label><input id="delete-code" name="code" type="text" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6,10}" minlength="6" maxlength="10" required aria-describedby="code-help"><small id="code-help">The code expires. Nothing is deleted just by verifying.</small></div><button class="button dark" type="submit">Verify and continue ${icon('arrow')}</button></form><button class="subtle-action" id="delete-restart" type="button">Use a different email or resend</button></section>
 <section id="delete-confirm-panel" hidden><h2>Delete this account?</h2><p class="form-privacy">Your email has been verified. This permanently removes your FirstLane account and its synced study history. It does not request a store refund.</p><form id="delete-confirm-form" novalidate><label class="confirm-checkbox"><input type="checkbox" id="delete-ack" required><span>I understand that deletion is permanent, removes synced history, and may prevent restoring purchases to this FirstLane account.</span></label><div class="field"><label for="delete-confirm-text">Type DELETE to confirm</label><input id="delete-confirm-text" autocomplete="off" autocapitalize="characters" spellcheck="false" maxlength="6" required></div><button class="button danger" type="submit">Permanently delete account ${icon('trash')}</button></form><button class="subtle-action" id="delete-cancel" type="button">Keep my account</button></section>
 <section id="delete-success-panel" class="deletion-success" hidden><div class="success-check">${icon('check')}</div><h2>Your FirstLane account<br>has been deleted.</h2><p>The account service has confirmed deletion. Eligible retained records and backups are handled as described in the <a href="privacy.html#retention">Privacy policy</a>. No refund has been requested.</p><a class="button outline" href="index.html">Back to FirstLane ${icon('arrow')}</a></section>
 <div class="form-status" id="delete-status" role="status" aria-live="polite"></div><noscript><p class="service-unavailable">JavaScript is required to verify ownership securely. You can also initiate deletion in FirstLane or contact support for help.</p></noscript><p class="form-privacy" id="delete-privacy-note">We use your email and verification code only for this account action. <a href="privacy.html">Privacy policy</a>.</p></div></div>`;}
export function cookies(){return policy('Cookies &amp; preferences','A small amount of useful memory. No advertising trackers.',`<strong>No cookie wall. No advertising pixels.</strong><p>This website does not set analytics or advertising cookies. You can browse the product and legal pages without accepting marketing tracking.</p>`,[
 ['preferences','1. Website preferences',`<p>When you pause website animations, FirstLane stores a small preference called <code>firstlane.motion</code> in your browser’s local storage. This stays on your device until you change it or clear site data. It is not used to recognise you on other websites or to build an advertising profile.</p><p>Your device’s reduced-motion setting is respected automatically. You can also use the “Pause animations” control at the bottom of any page.</p><button type="button" class="button outline" id="reset-preferences">Reset website preferences ${icon('refresh')}</button><div id="preferences-status" role="status" aria-live="polite" class="form-status"></div>`],
 ['security','2. Security on forms',`<p>The support and account-deletion forms use Cloudflare Turnstile to limit abuse. When you interact with a protected form, Turnstile processes technical security signals. This website does not enable Turnstile’s optional pre-clearance cookie.</p><p>Temporary account-deletion authentication is held in memory for the current page. We do not save your verification code or account access token in cookies or local storage. Closing or reloading the page clears that in-memory flow. The authentication provider may retain limited security logs.</p>`],
 ['external','3. Leaving this website',`<p>App Store, Google Play and other external pages have their own privacy and cookie practices. Opening those pages does not give this website access to their cookies or your payment information.</p>`],
 ['control','4. Your controls',`<p>You can clear site data or block storage in your browser. The website remains readable when local storage is unavailable; your animation preference may no longer persist between visits. See the <a href="privacy.html">Privacy policy</a> for other data practices, or ${contact(true)}.</p>`]
]);}
export function notFound(){return `<div class="wrap error-page"><span class="error-number">404 / A SMALL DETOUR</span><h1>Not quite<br><em>the right turn.</em></h1><img src="assets/journey.svg" width="640" height="540" alt="A winding road leading to a destination"><p>This page isn’t here, but your road ahead still is. Let’s get you back to FirstLane.</p><a class="button dark" href="index.html">Back to FirstLane ${icon('arrow')}</a></div>`;}
